### ISSUE TITLE
.env or yaml instead of json config file

### ISSUE THREAD

**Issue by ingria** [EmiXLabs/dbConnect#12]
JSON is not so good as config storage. 
I suggest either using the environment variables, or something more user-friendly, as yaml

**Comment by mastizada** [comment]
Json will stay as preferred method for configuration file as its python built-in. There will be additional support for os.environment and yaml if pyyaml is installed in environment (will check .yaml extension in file name).

**Comment by ingria** [comment]
Ok, fair. What about configparser and .ini format? It's built-in too.

**Comment by mastizada** [comment]
As it supports parameters, reading configuration in any preferred way and sending them using `DBConnect(**settings)` will solve problem and give flexibility for developer. Need to update docs.
