### ISSUE TITLE
autocommit

### ISSUE THREAD

**Issue by mertoksuz** [EmiXLabs/dbConnect#8]
Hi,

Need to set autocommit true / false for multiple select queries. Sometimes each query needs to be committed automatically.

In **MySQLdb** i can set it like that;

`connection.autocommit(True)`

**Comment by mastizada** [comment]
Thanks for reporting. Will make minor update to add this functionality.

**Comment by mastizada** [comment]
Fixed in Pull Request #9 
Add autocommit=True in connection parameters or in settings file.
